language: ruby
rvm:
- 2.0.0
language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql

before_script:
  - cp ./config/database.yml.template ./config/database.yml
  - psql -c 'create database motorss_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
